spring.application.name=demo

# MySQL Database Connection
# It will look for DB_URL in .env/system, else defaults to localhost
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/secure_bank?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Amaan@78}

# Hibernate / JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

# Server Port
server.port=${SERVER_PORT:4040}

# Health Check
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always